# Generated by Django 2.2.22 on 2022-05-10 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone_um', models.CharField(max_length=15, verbose_name='Telefone')),
                ('telefone_dois', models.CharField(blank=True, max_length=15, null=True, verbose_name='Outro Telefone')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('logradouro', models.CharField(max_length=250, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº')),
                ('complemento', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nº')),
                ('cidade', models.CharField(max_length=100, verbose_name='Nº')),
                ('email', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('data_alteracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração:')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro:')),
            ],
            options={
                'db_table': 'alunoapp_estudantes',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.CharField(choices=[('1', 'Português'), ('2', 'Matemática'), ('3', 'Ciências'), ('4', 'Artes'), ('5', 'Educação Física')], max_length=1)),
                ('dia_semana', models.CharField(choices=[('1', 'Segunda'), ('2', 'Terça'), ('3', 'Quarta'), ('4', 'Quinta'), ('5', 'Sexta')], max_length=1)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_termino', models.TimeField(blank=True, null=True)),
                ('data_alteracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração:')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro:')),
            ],
            options={
                'db_table': 'alunoapp_turma',
            },
        ),
        migrations.CreateModel(
            name='HistoricalAluno',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('telefone_um', models.CharField(max_length=15, verbose_name='Telefone')),
                ('telefone_dois', models.CharField(blank=True, max_length=15, null=True, verbose_name='Outro Telefone')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('logradouro', models.CharField(max_length=250, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nº')),
                ('complemento', models.CharField(blank=True, max_length=160, null=True, verbose_name='Nº')),
                ('cidade', models.CharField(max_length=100, verbose_name='Nº')),
                ('email', models.CharField(max_length=100)),
                ('ativo', models.BooleanField()),
                ('data_alteracao', models.DateTimeField(blank=True, null=True, verbose_name='Data de alteração:')),
                ('data_cadastro', models.DateTimeField(blank=True, editable=False, verbose_name='Data de cadastro:')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical aluno',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AlunoTurma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro:')),
                ('aluno', models.ForeignKey(db_column='aluno', on_delete=django.db.models.deletion.DO_NOTHING, to='AlunoApp.Aluno')),
                ('turma', models.ForeignKey(db_column='turma', on_delete=django.db.models.deletion.DO_NOTHING, to='AlunoApp.Turma')),
            ],
            options={
                'db_table': 'alunoapp_aluno_turma',
            },
        ),
    ]
