# Generated by Django 2.2.22 on 2022-05-10 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='data_nasc',
        ),
        migrations.RemoveField(
            model_name='historicalaluno',
            name='data_nasc',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='ativo',
            field=models.BooleanField(verbose_name='Aluno está Devidamente ativo'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='ativo',
            field=models.BooleanField(verbose_name='Aluno está Devidamente ativo'),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='cidade',
            field=models.CharField(max_length=100, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='complemento',
            field=models.CharField(blank=True, max_length=160, null=True, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
    ]
