# Generated by Django 2.2.22 on 2022-05-11 01:33

import cpf_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlunoApp', '0003_auto_20220510_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='historicalaluno',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=11, verbose_name='CPF'),
        ),
    ]
